[package]
name = "intmap"
version = "0.3.0"
description = "Specialized HashMap for u64 keys"
authors = ["Jesper Axelsson <jesperaxe@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/JesperAxelsson/rust-intmap"
keywords = ["hashmap", "u64", "intmap"]

[dependencies]

[dev-dependencies]
rand = "0.3"
fnv = "1.0"
